const menu = [
  {
    id: 1,
    title: 'granola dust waffles',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-11.jpeg',
    desc: `Wicked waffles topped with  yoghurt, fresh fruit and a drizzle of honey `,
  },
  {
    id: 2,
    title: 'roasted black bean burger',
    category: 'lunch',
    price: 20.99,
    img: './images/item-14.jpeg',
    desc: `Wedged into a bun with zingy tomato salsa, juicy mango, avocado and extra Tabasco, these black bean burgers are really something rather special `,
  },
  {
    id: 3,
    title: 'oat, pear & cardamom smoothie',
    category: 'drinks',
    price: 9.99,
    img: './images/item-17.jpeg',
    desc: `Natural smoothie with oat milk, pear, cardamom, yoghurt, honey and bee pollen `,
  },
  {
    id: 4,
    title: 'avocado & bacon eggy crumpets',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-12.jpeg',
    desc: `Chilli, eggy crumpet, topped with crispy bacon and creamy avocado – plus Parmesan crown and green chilli sauce`,
  },
  {
    id: 5,
    title: 'tomato & caper linguine',
    category: 'lunch',
    price: 18.99,
    img: './images/item-15.jpeg',
    desc: `Linguine with tomato passata, capers, lemon and parmesan cheese  `,
  },
  {
    id: 6,
    title: 'summer cordial',
    category: 'drinks',
    price: 8.99,
    img: './images/item-18.jpeg',
    desc: `Stunning summer cordial made with raspberries and lemons `,
  },
  {
    id: 7,
    title: 'mango & yoghurt layer pots',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-13.jpeg',
    desc: `Pots filled with yoghurt, mango and granola dust perfect for breakfast`,
  },
  {
    id: 8,
    title: 'sticky sesame prawns',
    category: 'lunch',
    price: 22.99,
    img: './images/item-16.jpeg',
    desc: `Prawns and Asian flavours together with the miso, ginger, sesame and chilli combo   `,
  },
  {
    id: 9,
    title: 'elderflower lemonade with frozen berries',
    category: 'drinks',
    price: 12.99,
    img: './images/item-19.jpeg',
    desc: `Elderflower cocktail with berries, lemons and sparkling water `,
  },
];
export default menu;
